<?php /** @var Thecoachsmb\Mymodule\Block\Article $block */ ?>
<?php $articleCollection = $block->getCollection(); ?>
<?php if (count($articleCollection)) { ?>
      <h2><?= $block->escapeHtml(__('Thecoachsmb Articles')) ?></h2>
      <?php foreach($articleCollection as $post): ?>
           <h3><?= $block->escapeHtml(__('Article - ')) ?>
               <a href="<?php echo $block->getArticleUrl($post->getId());?>"><?php echo $post->getTitle(); ?></a> 
           </h3> 
           <h4><?php echo date('F j, Y', strtotime($post->getCreatedAt())); ?></h4>
           <p><?php echo $post->getContent(); ?></p> 
     <?php endforeach; ?> 
<?php } ?> 


<form method="POST" name="review_form" id="review_form">
    <span>Title:<input name="title" id="title" title="title" class="title" type="text"></span>
    <span>Content:<input name="content" id="content" title="content" class="content" type="text"><br></span>
    <br><button id="submit_demo_data">Submit Review</button>
</form>

<script type="text/javascript">
    require([
        "jquery",
        "mage/mage"
    ],function($) {
        $(document).ready(function() {
            $('#review_form').mage(
                'validation',
                {
                    submitHandler: function(form) {
                        var customurl = "<?php echo $this->getUrl().'rest/V1/article'?>";
                        var articleData = {
                            article: {
                                title: $('#title').val(),
                                content: $('#content').val()
                            }
                        };
                        $.ajax({
                            url: customurl,
                            data: JSON.stringify(articleData),
                            type: 'POST',
                            dataType: 'json',
                            contentType: 'application/json',
                            showLoader: true,
                            cache: false,
                            success: function(data, status, xhr) {
                                console.log(data);
                               
                            },
                            error: function (data, xhr, status, errorThrown) {
                                console.log(data);
                                console.log('Error happens. Try again.');
                                console.log(errorThrown);
                            }
                        });
                    }
                }
            );
        });
    });
</script>
